server:
  port: 8705
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/npde?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
#      url: jdbc:mysql://39.98.236.58:3306/npde?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 6y7u8i9o0p@2580abc
mybatis:
   type-aliases-package: tk.mybatis.springboot.model
   mapperLocations: classpath:/mapper/*.xml
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
   mapper:
       mappers:
           - com.heeexy.example.util.MyMapper
       not-empty: false
       identity: MYSQL

   pagehelper:
       helperDialect: mysql
       reasonable: true
       supportMethodsArguments: true
       params: count=countSql
