spring:
  datasource:
      url: jdbc:mysql://localhost:3306/npde?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
